introduction:
- "&2&l LoreCrafting&r &0&l ============&r\nWelcome to LoreCraft, this book will guide you though the mystical and magical world of Lore crafting.\nThe existence of Lore has been known since the beginning of time with many\nmyths and superstitions have"
- "been built around it. However, no-one had been able to tame this most primalof magical forces.\nLittle is actually known as to why Lore exists but many believe that it is the force of nature which binds this world together."
- "The most powerful Arch-Mages through out all the kingdoms have spent many centuries trying to study and understand the Lore so that they can bend it to their will and many have died in their endeavour."
- "Only recently when the kingdoms have finally come to exist in harmony and joined their efforts have the Arch-Mages, working with the Elders and Druids finally begun to learn how to unlock this most powerful resource."
- "Although Lore can be found in almost every item, only a few have been found in which the Lore can be extracted and worked with.\nIt is still unclear what common threads tie these objects together and so unlocking the full potential of Lore has been, and"
- "continues to be a slow process."
objects:
- enchantments
- wandofreplacement
- wandofenlightenment