type: lorecraftinformation
permissionnode: wandofreplacement
chaptername: "Enchantments"
pages:
- "&d&lEnchantments&r&0\nDue to the magical forces already infused into LoreCraft items they can't be enchanted via the enchantment table, such a mix of powers could prove highly unstable.\nHowever, it has proven possible for enchantments that have already been"
- "stored on books to be safely applied."